server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: rate-limiter-route
              uri: http://rate-limiter-service:8082 # Forward to our rate-limiter-service
              predicates:
                - Path=/api/** # Match any request starting with /api/
              filters:
                - StripPrefix=1 # Remove the first part of the path (i.e., /api)

management:
  endpoints:
    web:
      exposure:
        include: health,prometheus